[build]
  functions = "functions"
  publish = "dist" 

[dev]
  publish = "dist"
  autoLaunch = false

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200